[package]
name = "cryptopals_rust"
version = "0.1.0"
authors = ["aguestuser <aguestuser@riseup.net>"]
edition = "2018"

[dependencies]
base64 = "0.10.0"
hex = "0.3.2"
lazy_static = "1.2.0"
num = "0.2.0"
